language: perl

matrix:
  include:
    - perl: "5.30"
    - perl: "5.22"
    - perl: "5.20"
      dist: trusty
    - perl: "5.16"
      dist: trusty
    - perl: "5.10"
      dist: trusty

env:
  global:
    - HARNESS_OPTIONS=j5

sudo: false
notifications:
  email: false

before_install:
  - cpanm --installdeps -n -q .
  - cpanm -n -q Devel::Cover Devel::Cover::Report::Coveralls

install:
  - true

script:
  - cover -t +select ^asub +ignore ^t -make 'prove -v; exit $?; '

after_success:
  - cover -report coveralls
